/* eslint-disable prettier/prettier */

// Fetch Data. (first)
export const FETCHING_REALTIMEDB_DOOR = 'FETCHING_REALTIMEDB_DOOR';
export const FETCHING_REALTIMEDB_DOOR_SUCCESS = 'FETCHING_REALTIMEDB_DOOR_SUCCESS';
export const FETCHING_REALTIMEDB_DOOR_FAILRUE = 'FETCHING_REALTIMEDB_DOOR_FAILRUE';

// Fetch Data. (update)
export const FETCHING_REALTIMEDB_DOOR_UPDATE = 'FETCHING_REALTIMEDB_DOOR_UPDATE';
export const FETCHING_REALTIMEDB_DOOR_UPDATE_SUCCESS = 'FETCHING_REALTIMEDB_DOOR_UPDATE_SUCCESS';
export const FETCHING_REALTIMEDB_DOOR_UPDATE_FAILRUE = 'FETCHING_REALTIMEDB_DOOR_UPDATE_FAILRUE';

// Fetch currentUser from firebase.
export const FIRST_LOAD_CURRENTUSER_FIREBASE = 'FIRST_LOAD_CURRENTUSER_FIREBASE';
export const FETCHING_REALTIMEDB_DOOR_LENGTHDATA = 'FETCHING_REALTIMEDB_DOOR_LENGTHDATA';
export const FIRST_LOAD_CURRENTUSER_FIREBASE_SUCCESS = 'FIRST_LOAD_CURRENTUSER_FIREBASE_SUCCESS';
export const FIRST_LOAD_CURRENTUSER_FIREBASE_FAILRUE = 'FIRST_LOAD_CURRENTUSER_FIREBASE_FAILRUE';

// Theme and Cache.
export const CACHETHEME_FETCHING = 'CACHETHEME_FETCHING';
export const SETTHEME_TO_STORE = 'SETTHEME_TO_STORE';
export const GETTHEME_FROM_CACHE_SUCCESS = 'GETTHEME_FROM_CACHE_SUCCESS';

// Navigation
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const DELETE_NAVIGATION = 'DELETE_NAVIGATION';
export const SETTING_NOTIFICATION = 'SETTING_NOTIFICATION';
export const SETTING_STATUS = 'SETTING_STATUS';
export const SETTING_MESSAGE = 'SETTING_MESSAGE';

// Message
export const GET_MESSAGES = 'GET_MESSAGES'
export const SET_MESSAGES = 'SET_MESSAGES'

// Connection arduino & app
export const SET_CONNECTION_CHANGED = 'SET_CONNECTION_CHANGED'

