// Auth
export const USER_LOGOUT = 'USER_LOGOUT';

// CurrentUserReducer
export const LOAD_CURRENT_USER_FIREBASE = 'LOAD_CURRENT_USER_FIREBASE';

// Fetch Data. (first)
export const FETCHING_REALTIMEDB_DOOR_SUCCESS =
  'FETCHING_REALTIMEDB_DOOR_SUCCESS';
export const FETCHING_REALTIMEDB_DOOR_FAILRUE =
  'FETCHING_REALTIMEDB_DOOR_FAILRUE';

// Theme
export const SET_THEME = 'SET_THEME';
export const SET_THEME_SYSDEFAULT = 'SET_THEME_SYSDEFAULT';
export const SET_THEME_DARKMODE = 'SET_THEME_DARKMODE';

// Navigation
export const SET_NOTIFICATION = 'SET_NOTIFICATION';
export const DELETE_NOTIFICATION = 'DELETE_NOTIFICATION';
export const SETTING_NOTIFICATION = 'SETTING_NOTIFICATION';
export const SETTING_STATUS = 'SETTING_STATUS';
export const SETTING_MESSAGE = 'SETTING_MESSAGE';
export const SETALLNOTIFICATION_TOSTORE = 'SETALLNOTIFICATION_TOSTORE';
export const VALIDATION_DATE_NOTIFICATION = 'VALIDATION_DATE_NOTIFICATION';

// Message
export const GET_MESSAGES = 'GET_MESSAGES';
export const SET_MESSAGES = 'SET_MESSAGES';

// Add product
export const SET_PRODUCTKEY_TOSTORE = 'SET_PRODUCTKEY_TOSTORE';
export const SET_BUSY_ON = 'SET_BUSY_ON';
export const SET_BUSY_OFF = 'SET_BUSY_OFF';
export const PRODUCTKEY_CONNECTED = 'PRODUCTKEY_CONNECTED';
export const PRODUCTKEY_NOT_YET_CONNECTION = 'PRODUCTKEY_NOT_YET_CONNECTION';
export const PRODUCTKEY_NOT_FOUND = 'PRODUCTKEY_NOT_FOUND';
export const RESET_ISKEY = 'RESET_ISKEY';

// User connection
export const FETCH_USER_CONNECTION_SUCCESS = 'FETCH_USER_CONNECTION_SUCCESS';
export const RESET_USER_CONNECTION = 'RESET_USER_CONNECTION';

// NetInfo
export const FETCH_NETINFO = 'FETCH_NETINFO';
